Jcode/Jcode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'),namespace='app')),
    path('video/', include(('video.urls','video'),namespace='video')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Jcode/app/urls.py
from django.urls import path,re_path
from . import views
urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('signup/', views.signup_view,name='signup'),
    path('profile/', views.profile_management,name='profile'),

]

Jcode/video/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index,name='index'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    path("course/", views.management_course, name='management_course'),
    path("chapter/", views.management_chapter, name="management_chapter"),
    path("lesson/", views.management_lesson, name="management_lesson"),
    path('deletevideo/<int:id>', views.video_delete, name='video_delete'),
    path('deletechapter/<int:id>', views.chapter_delete, name='chapter_delete'),
    path('deletelesson/<int:id>', views.lesson_delete, name='lesson_delete'),
    path('updatevideo/<int:id>',views.update_video,name='update_course'),
    path('updatechapter/<int:id>',views.update_chapter,name='update_chapter'),
    path('updatelesson/<int:id>',views.update_lesson,name='update_lesson'),
    path('add/', views.video_add, name='video_add'),
    path('addchapter/', views.video_addchapter, name='video_addchapter'),
    path('addlesson/', views.video_addlesson, name='video_addlesson'),
]

Jcode/video/models.py
from django.db import models
from app.models import Category,CategorySub,Member
# Create your models here.
class Video(models.Model):
    member = models.ForeignKey(Member,null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=450)
    description = models.TextField(null=True, blank=True)
    image = models.FileField(upload_to='video', null=True, blank=True)
    videoexample=models.FileField(upload_to='video/example', null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    category_sub = models.ForeignKey(CategorySub, null=True, blank=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, default=0)
    price_before = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, default=0)
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_chapter_set_with_ordered(self):
        return self.videolesson_set.order_by('chapter__ordered','ordered')

    def __str__(self):
        return self.name

    @classmethod
    def search(cls, query):
        return cls.objects.filter(title__icontains=query) | cls.objects.filter(content__icontains=query)


class VideoChapter(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    ordered = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class VideoLesson(models.Model):
    videos = models.ForeignKey(Video, on_delete=models.CASCADE,default=1)
    chapter = models.ForeignKey(VideoChapter, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    duration_time = models.CharField(max_length=15, null=True, blank=True)
    lessonvideo = models.FileField(upload_to='video/lesson/video', null=True, blank=True)
    video_url = models.CharField(max_length=450, null=True, blank=True)
    is_locked = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ordered = models.IntegerField(default=0)

    def __str__(self):
        return self.name

Jcode/video/forms.py
from django import forms
from .models import Video,VideoChapter,VideoLesson

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        exclude = ['id','member', 'slug', 'published', 'created', 'updated']
        labels ={
            'name':'ชื่อ',
            'description':'รายละเอียด',
            'image':'ภาพคอร์ส',
            'videoexample':'วิดีโอตัวอย่าง',
            'category':'ประเภทหลัก',
            'category_sub':'ประเภทย่อย',
            'price':'ราคา',
            'price_before':'ราคาเต็ม'
        }

class VideochapterForm(forms.ModelForm):
    class Meta:
        model = VideoChapter
        exclude = ['id','video', 'created', 'updated']
        labels ={
            'name':'ชื่อ',
            'ordered':'ลำดับ'
        }

class VideolessonForm(forms.ModelForm):
    class Meta:
        model = VideoLesson
        exclude = ['id','videos','chapter', 'created', 'updated']
        labels ={
            'name':'ชื่อ',
            'duration_time':'ระยะเวลา',
            'lessonvideo':'วิดีโอ',
            'video_url':'ลิงค์วิดีโอ',
            'is_locked':'ดูได้เฉพาะผู้ซื้อคอร์สแล้ว',
            'ordered':'ลำดับ',
        }

Jcode/video/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView, DetailView
from .models import Video,VideoLesson,VideoChapter
from .models import Category,CategorySub,Member
from .forms import VideoForm,VideochapterForm,VideolessonForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from slugify import slugify


def index(request):
    video = Video.objects.filter(published=True)
    context = {'video_list':video,}

    return render(request,'video/index.html',context)


class BookDetailView(DetailView):
    model = Video
    template_name = 'video/detail.html'
    slug_url_kwarg = 'slug'


#------------------------------------------------------
#chapter management
#------------------------------------------------------


def management_course(request):
    videos = Video.objects.filter(member__user=request.user.id)
    return render(request,'video/course.html',{"video_list":videos})


def video_add(request):
    form = VideoForm()
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.slug = slugify(video.name)
            video.member = Member.objects.filter(user_id=request.user.id).first()
            video.published = True
            video.save()
            form.save_m2m()
            messages.success(request, 'บันทึกสำเร็จ')
            return HttpResponseRedirect(reverse('video:management_course'))
        messages.error(request, 'บันทึกไม่สำเร็จ!')
    return render(request, 'video/add.html', {
        'form': form,
    })


def update_video(request, id):
    videos= Video.objects.get(id=id)
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES, instance=videos)
        if form.is_valid():
            form.save()
            messages.success(request, 'บันทึกสำเร็จ')
            return redirect('video:management_course')
    else:
        form = VideoForm(instance=videos)
    return render(request, 'video/update_video.html', {'form': form})


def video_delete(request, id):
    videos = Video.objects.get(id=id)
    videos.delete()
    messages.success(request, 'ลบสำเร็จ')
    return redirect(reverse('video:management_course'))


#------------------------------------------------------
#chapter management
#------------------------------------------------------


def management_chapter(request):
    courseid=request.GET.get('courseid')
    chapters = VideoChapter.objects.filter(video__id=courseid)
    return render(request,'video/chapter.html',{"chapters_list":chapters,"courseid":courseid})


def video_addchapter(request):
    form = VideochapterForm()
    courseid=request.GET.get('courseid')
    if request.method == 'POST':
        form = VideochapterForm(request.POST, request.FILES)
        if form.is_valid():
            chapter = form.save(commit=False)
            chapter.video_id=courseid
            chapter.save()
            form.save_m2m()
            messages.success(request, 'บันทึกสำเร็จ')
            return HttpResponseRedirect(reverse('video:management_chapter')+'?courseid='+str(courseid))
        messages.error(request, 'บันทึกไม่สำเร็จ!')
    return render(request, 'video/add_chapter.html', {
        'form': form,
    })


def update_chapter(request, id):
    courseid=request.GET.get('courseid')
    chapters= VideoChapter.objects.get(id=id)
    if request.method == 'POST':
        form = VideochapterForm(request.POST,  instance=chapters)
        if form.is_valid():
            form.save()
            messages.success(request, 'บันทึกสำเร็จ')
            return redirect(reverse('video:management_chapter')+'?courseid='+str(courseid))
    else:
        form = VideochapterForm(instance=chapters)
    return render(request, 'video/update_chapter.html', {'form': form,'courseid':courseid})


def chapter_delete(request, id):
    courseid=request.GET.get('courseid')
    chaptervideo = VideoChapter.objects.get(id=id)
    chaptervideo.delete()
    messages.success(request, 'ลบสำเร็จ')
    return redirect(reverse('video:management_chapter')+'?courseid='+str(courseid))



#------------------------------------------------------
#lesson management
#------------------------------------------------------


def management_lesson(request):
    courseid=request.GET.get('courseid')
    chapterid=request.GET.get('chapterid')
    lesson = VideoLesson.objects.filter(chapter__id=chapterid)
    return render(request,'video/lesson.html',{"lesson_list":lesson,"courseid":courseid,"chapterid":chapterid})


def video_addlesson(request):
    form = VideolessonForm()
    courseid=request.GET.get('courseid')
    chapterid=request.GET.get('chapterid')
    if request.method == 'POST':
        form = VideolessonForm(request.POST, request.FILES)
        if form.is_valid():
            lesson_obj = form.save(commit=False)
            lesson_obj.videos_id=courseid
            lesson_obj.chapter_id=chapterid
            lesson_obj.save()
            form.save_m2m()
            messages.success(request, 'บันทึกสำเร็จ')
            return redirect(reverse('video:management_lesson')+'?courseid='+str(courseid)+'&chapterid='+str(chapterid))
        messages.error(request, 'บันทึกไม่สำเร็จ!')
    return render(request, 'video/add_lesson.html', {
        'form': form,
        'courseid':courseid,
        'chapterid':chapterid,
    })


def update_lesson(request, id):
    courseid=request.GET.get('courseid')
    chapterid=request.GET.get('chapterid')
    lessons= VideoLesson.objects.get(id=id)
    if request.method == 'POST':
        form = VideolessonForm(request.POST,  instance=lessons)
        if form.is_valid():
            lesson_obj = form.save(commit=False)
            lesson_obj.videos_id=courseid
            lesson_obj.chapter_id=chapterid
            form.save()
            messages.success(request, 'แก้ไขสำเร็จ')
            return redirect(reverse('video:management_lesson')+'?courseid='+str(courseid)+'&chapterid='+str(chapterid))
    else:
        form = VideolessonForm(instance=lessons)
    return render(request, 'video/update_lesson.html', {
        'form': form,
        'courseid':courseid,
        'chapterid':chapterid,
        })

def lesson_delete(request, id):
    courseid=request.GET.get('courseid')
    chapterid=request.GET.get('chapterid')
    lessonvideo = VideoLesson.objects.get(id=id)
    lessonvideo.delete()
    messages.success(request, 'ลบสำเร็จ')
    return redirect(reverse('video:management_lesson')+'?courseid='+str(courseid)+'&chapterid='+str(chapterid))

Jcode/templates/video/add.html
{% extends "layout/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h1>Add Video</h1>
            <form method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Jcode/templates/video/add_chapter.html
{% extends "layout/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h3 style="text-align: center;"><b>เพิ่ม Chapter</b></h3>
            <form method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success">บันทึก</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Jcode/templates/video/add_lesson.html
{% extends "layout/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h3 style="text-align: center;"><b>เพิ่มบทเรียน</b></h3>
            <form method="post" enctype="multipart/form-data" novalidate action="?courseid={{courseid}}&chapterid={{chapterid}}">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success">บันทึก</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Jcode/templates/video/chapter.html
{% extends "layout/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
      <h3 style="text-align: center;"><b>จัดการ Chapter</b></h3>
      <h5 style="float: left;"><i class="fa fa-chevron-left"></i><a href="{% url 'video:management_course' %}"> ย้อนกลับ</a></h5>
        <div class="col-lg-8 offset-lg-2">
            <div style="text-align: center;">
              <a class="btn btn-addchapter mt-2" href="{% url 'video:video_addchapter' %}?courseid={{courseid}}">เพิ่มChapter </a>
            </div>
            <table class="my-4">
              <tr>
                <th>หัวข้อหลัก</th>
                <th>ลำดับ</th>
                <th colspan="2">Action</th>
              </tr>
              {% for chapter in chapters_list %}
              <tr>
                <td><a href="{% url 'video:management_lesson' %}?courseid={{courseid}}&chapterid={{chapter.id}}">{{ chapter.name }}</a></td>
                <td>{{ chapter.ordered }}</td>
                <td><a href="{% url 'video:update_chapter' id=chapter.id %}?courseid={{courseid}} ">แก้ไข</a> </td>
                <td><a href="javascript:deletechapter({{chapter.id}})" style="color: #FF0404;">ลบ</a></td>
              </tr>
              {% endfor %}
            </table>
        </div>
    </div>
</div>
<script>
  function deletechapter(chapterid){
    Swal.fire({
      title: 'คุณต้องการลบ Chapter นี้ ?',
      text: "เมื่อลบแล้วจะไม่สามารถนำข้อมูลกลับมาได้ !",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#0CB009',
      cancelButtonColor: '#d33',
      cancelButtonText: 'ยกเลิก',
      confirmButtonText: 'ยืนยัน !'
    }).then((result) => {
      if (result.isConfirmed) {
        window.location.href="/video/deletechapter/"+chapterid+"?courseid={{courseid}}"
      }
    })
  }
</script>
{% endblock %}

Jcode/templates/video/chapter_confirm_delete.html
<h1>Delete Article</h1>
<p>Are you sure you want to delete "{{ chapters.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>

Jcode/templates/video/course.html
{% extends "layout/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <h3 style="text-align: center;"><b>จัดการคอร์สออนไลน์</b></h3>
        <h5 style="float: left;"><i class="fa fa-chevron-left"></i><a href="{% url 'video:index' %}"> ย้อนกลับ</a></h5>
        <div class="col-lg-8 offset-lg-2">
            <div style="text-align: center;">
              <a class="btn btn-createcourse mt-2" href="{% url 'video:video_add'  %}">เพิ่มคอร์สเรียน</a>
            </div>
           <table class="manage_course my-4">
            <tr>
              <th>คอร์ส</th>
              <th>บทเรียน</th>
              <th>ราคา</th>
              <th>สถานะ</th>
              <th colspan="2">จัดการ</th>
            </tr>
            {% for video in video_list %}
            <tr>
              <td><a href="{% url 'video:management_chapter'  %}?courseid={{video.id}}">{{ video.name }}</a></td>
              <td>{{ video.videolesson_set.count }}</td>
              <td>{{ video.price }} ฿</td>
              {% if video.published == True%}
              <td style="color: #0CB009;"><b>Published</b></td>
              {% elif video.published == False %}
              <td style="color: #FF0404;"><b>No Published</b></td>
              {% endif %}
              <td><a href="{% url 'video:update_course' id=video.id %}">แก้ไข</a></td>
              <td><a href="javascript:deletecourse({{video.id}})" style="color: #FF0404;">ลบ</a></td>
            </tr>
            {% endfor %}
          </table>
        </div>
    </div>
</div>
<script>
  function deletecourse(courseid){
    Swal.fire({
      title: 'คุณต้องการลบ Chapter นี้ ?',
      text: "เมื่อลบแล้วจะไม่สามารถนำข้อมูลกลับมาได้ !",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#0CB009',
      cancelButtonColor: '#d33',
      cancelButtonText: 'ยกเลิก',
      confirmButtonText: 'ยืนยัน !'
    }).then((result) => {
      if (result.isConfirmed) {
        window.location.href="/video/deletevideo/"+courseid
      }
    })
  }
</script>
{% endblock %}

Jcode/templates/video/detail.html
{% extends "layout/base.html" %}

{% block content %}
<div class="subnav mb-5">
    <div class="container">
      <div class="pricetag">
        โปรโมชั่น
        <h3>฿{{ video.price }}</h3>
      </div>
      <h1>{{ video.name }}</h1>
      <a href="{% url 'video:index' %}"class='text-white'><i class="fa fa-chevron-left"></i>ย้อนกลับ</a>
    </div>
  </div>
  {% regroup video.get_chapter_set_with_ordered by chapter as chapter_list %}
        {% if video.videoexample %}
        <video id="videoplayer" controls width="400" height="300">
          <source src="http://192.168.1.6:8000{{video.videoexample.url}}" type="video/mp4" >
          Your browser does not support HTML5 video.
        </video>
        {% endif %}
        <div class="row g-5">
          <div class="col-lg-8">
            <div class="accordion mb-5" id="accordionExample">
              {% for chapter in chapter_list %}
                <div class="card">
                  <div class="card-header" id="heading{{ forloop.counter }}">

                      <button class="btn " type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                        {{ chapter.grouper }}
                      </button>

                  </div>

                  <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordionExample">
                    <div class="card-body">
                      <table class="table table-bordered table-hover">
                        <tbody>
                          {% for lesson in chapter.list %}
                            <tr>
                              <td>{{ lesson.name }}</td>
                              <td><i class="far fa-clock"></i> {{ lesson.duration_time }}</td>
                              {% if lesson.lessonvideo %}
                              {% if lesson.is_locked == False %}
                                <td><button videourl='http://192.168.1.6:8000{{lesson.lessonvideo.url}}' class="btn-play"><i class="far fa-circle-play"></i>videoplay</button></td>
                              {% elif lesson.is_locked == True %}
                                <td><i class="fa fa-lock"></i></td>
                              {% endif %}
                              {% endif %}
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
      </div>
    </div>

      <div class="col-lg-4">
        <a href="#"class='btn btn-success btn-lg py-3 w-100'>สั่งซื้อคอร์สนี้</a>
        <div class="my-4">
          <h5>รายละเอียด</h5>
          {{ video.description }}
        </div>
        <div class="profile my-4">
          <h4>ประวัติผู้สอน</h4>

        </div>
      </div>


  <div class="container">
    <div class="row mb-4">
        <div class="col-lg-3">
            {% if video.image %}
            <img src="{{ video.image.url }}" class="img-fluid" alt="">
            {% endif %}
        </div>
        <div class="col-lg-9">
            <h1>{{ video.name }}</h1>
            <strong>Author</strong>
            <span class="">{{ video.member }}</span>
            <div class="mt-4 mb-4"></div>
            <h5 class="mb-4">฿ {{ video.price }} {{video.member.description}} {{video.member.user.first_name}}</h5>
            <img src="{{video.member.Profile_image.url}}" alt="" >
        </div>
    </div>
  </div>

{% endblock %}

Jcode/templates/video/index.html
{% extends "layout/base.html" %}

{% load static %}

{% block title %} Video Page {% endblock %}

{% block content %}




<div class="container">
  <div class="mb-4">
    <h6><b>คอร์สแนะนำ</b></h6>
  </div>
    <div class="row">
      {% for b in video_list %}


      <div class="col-lg-3 d-flex align-items-stretch">

        <div class="card card-course mb-4">


          <a href="#">
            {% if b.image %}
            <img src="{{b.image.url}}" alt="" class="card-img-top" >
            {% endif %}
          </a>


        <div class="card-body">
          <div class="profile">


            <img src="{{b.member.Profile_image.url}}" alt="" >


          </div>
          <h5><a href="{% url 'video:detail' slug=b.slug %}">{{b.name}} </a></h5>
          <h4></h4>
          <div class="small">
            <i class="fa fa-video"></i>
            {{ b.videolesson_set.count }} บทเรียน
          </div>

        <div class="small rating">
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star-half"></i>
          <span>(3.5)</span>
        </div>

        </div>

        <div class="card-footer border-0 bg-transparent">
          <h5>฿ {{b.price}} {{b.member}} {{c.user_code}}</h5>
        </div>

        </div>



      </div>

      {% endfor %}
    </div>




    <div class="mb-4">
      <h6><b>คอร์สทั้งหมด</b></h6>
    </div>
    <div class="row">
      {% for b in video_list %}


      <div class="col-lg-3 d-flex align-items-stretch">

        <div class="card card-course mb-4">


          <a href="#">
            {% if b.image %}
            <img src="{{b.image.url}}" alt="" class="card-img-top" >
            {% endif %}
          </a>


        <div class="card-body">
          <div class="profile">


            <img src="{{b.member.Profile_image.url}}" alt="" >


          </div>
          <h5><a href="{% url 'video:detail' slug=b.slug %}">{{b.name}} </a></h5>
          <h4></h4>
          <div class="small">
            <i class="fa fa-video"></i>
            {{ b.videolesson_set.count }} บทเรียน
          </div>

        <div class="small rating">
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star-half"></i>
          <span>(3.5)</span>
        </div>

        </div>

        <div class="card-footer border-0 bg-transparent">
          <h5>฿ {{b.price}} {{b.member}} {{c.user_code}}</h5>
        </div>
        </div>
      </div>
      {% endfor %}
    </div>




  </div>
{% endblock %}

Jcode/templates/video/lesson.html
{% extends "layout/base.html" %}


{% block content %}

<div class="container">
    <div class="row">
      <h3 style="text-align: center;"><b>จัดการบทเรียน</b></h3>
          <h5 style="float: left;"><i class="fa fa-chevron-left"></i><a href="{% url 'video:management_chapter' %}?courseid={{courseid}}"> ย้อนกลับ</a></h5>
        <div class="col-lg-8 offset-lg-2">

          <div style="text-align: center;">
            <a class="btn btn-addlesson mt-2" href="{% url 'video:video_addlesson' %}?courseid={{courseid}}&chapterid={{chapterid}}">เพิ่มบทเรียน</a>
          </div>
          <table class="my-4">
            <tr>
              <th>หัวข้อหลัก</th>
              <th>บทเรียน</th>
              <th>ความยาว</th>
              <th>วิดีโอ</th>
              <th>สถานะ</th>
              <th>ลำดับ</th>
              <th colspan="2">Action</th>
            </tr>
            {% for lesson in lesson_list %}
            <tr>
              <td>{{ lesson.chapter.name}}</td>
              <td>{{ lesson.name }}</td>
              <td>{{ lesson.duration_time }}</td>
              <td>{{ lesson.lessonvideo }}</td>
              {% if lesson.is_locked == True %}
              <td style="color: #FF0404;">Locked</td>
              {% elif lesson.is_locked == False %}
              <td style="color:#0CB009">Free</td>
              {% endif %}
              <td>{{ lesson.ordered }}</td>
              <td><a href="{% url 'video:update_lesson' id=lesson.id %}?courseid={{courseid}}&chapterid={{chapterid}}">แก้ไข</a> </td>
              <td><a href="javascript:deletelesson({{lesson.id}})" style="color: #FF0404;">ลบ</a></td>
            </tr>
            {% endfor %}
          </table>
        </div>
    </div>
</div>
<script>
  function deletelesson(lessonid){
    Swal.fire({
      title: 'คุณต้องการลบ Chapter นี้ ?',
      text: "เมื่อลบแล้วจะไม่สามารถนำข้อมูลกลับมาได้ !",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#0CB009',
      cancelButtonColor: '#d33',
      cancelButtonText: 'ยกเลิก',
      confirmButtonText: 'ยืนยัน !'
    }).then((result) => {
      if (result.isConfirmed) {
        window.location.href="/video/deletelesson/"+lessonid+"?courseid={{courseid}}&chapterid={{chapterid}}"
      }
    })
  }
</script>
{% endblock %}

Jcode/templates/video/lesson_confirm_delete.html
<h1>Delete Article</h1>
<p>Are you sure you want to delete "{{ lessons.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>

Jcode/templates/video/update_chapter.html
{% extends "layout/base.html" %}

{% block content %}


<h3 style="text-align: center;"><b>แก้ไข chapter</b></h3>
<form method="post" enctype="multipart/form-data" action="?courseid={{courseid}}">
    {% csrf_token %}
    <div style="text-align: center;">
    {{ form.as_p }}
  </div>
  <div style="text-align: center;">
    <input type="submit" class="btn btn btn-update mx-2" value="Update">
  </div>
</form>
{% endblock %}

Jcode/templates/video/update_lesson.html
{% extends "layout/base.html" %}

{% block content %}


<h3 style="text-align: center;"><b>แก้ไข Lesson</b></h3>
<form method="post" enctype="multipart/form-data" action="?courseid={{courseid}}&chapterid={{chapterid}}">
    {% csrf_token %}
    <div style="text-align: center;">
    {{ form.as_p }}
  </div>
  <div style="text-align: center;">
    <input type="submit" class="btn btn btn-update mx-2" value="Update">
  </div>
</form>
{% endblock %}

Jcode/templates/video/update_video.html
{% extends "layout/base.html" %}

{% block content %}


<h3 style="text-align: center;"><b>จัดการคอร์สออนไลน์</b></h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="text-align: center;">
    {{ form.as_p }}
  </div>
  <div style="text-align: center;">
    <input type="submit" class="btn btn btn-update mx-2" value="Update">
  </div>
</form>
{% endblock %}

Jcode/templates/video/video_confirm_delete.html
{% extends "layout/base.html" %}

{% block content %}
<h3 style="text-align: center;"><b>ยืนยันการลบคอร์ส</b></h3>
<h6 style="text-align: center;">คุณต้องการที่จะลบคอร์ส "{{ videos.name }}" ใช่ไหม ?</h6>

<form method="post">
  <button type="">ยกเลิก</button>
<form method="post">
    {% csrf_token %}
    <button type="submit">ยืนยัน</button>

</form>
{% endblock %}