Jcode/Jcode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'),namespace='app')),
    path('video/', include(('video.urls','video'),namespace='video')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Jcode/app/urls.py
from django.urls import path,re_path
from . import views
urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('signup/', views.signup_view,name='signup'),
    path('profile/', views.profile_management,name='profile'),

]

Jcode/video/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index,name='index'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    path("course/", views.management_course, name='management_course'),
    path("chapter/", views.management_chapter, name="management_chapter"),
    path("lesson/", views.management_lesson, name="management_lesson"),
    path('deletevideo/<int:id>', views.video_delete, name='video_delete'),
    path('deletechapter/<int:id>', views.chapter_delete, name='chapter_delete'),
    path('deletelesson/<int:id>', views.lesson_delete, name='lesson_delete'),
    path('updatevideo/<int:id>',views.update_video,name='update_course'),
    path('updatechapter/<int:id>',views.update_chapter,name='update_chapter'),
    path('updatelesson/<int:id>',views.update_lesson,name='update_lesson'),
    path('add/', views.video_add, name='video_add'),
    path('addchapter/', views.video_addchapter, name='video_addchapter'),
    path('addlesson/', views.video_addlesson, name='video_addlesson'),
]

Jcode/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}jCode Academy{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kanit&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css" rel="stylesheet">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light  bg-white border-bottom mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'app:index' %}">jCode Academy</a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="d-flex">

          <div class="dropdown">
            <button class="btn btn-primary btn-category dropdown-toggle mx-2" type="button" id="dropdownMenuButton"
              data-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-bars"></i> ประเภท
            </button>
            {% regroup subcategory_list by category as category_list1 %}
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for category in category_list1 %}
              <li>
                <a class="dropdown-item" href="#">
                  {{ category.grouper }}
                  <i class="fa-solid fa-chevron-right" style="float: right;"></i>
                </a>

                <ul class="dropdown-menu dropdown-submenu">
                  {% for sub in category.list %}
                      <li>
                        <a class="dropdown-item" href="#">{{ sub.name }}</a>
                      </li>
                      {% endfor %}
                </ul>

              </li>{% endfor %}
            </ul>
          </div>

        <div class="navbar-search">
          <i class="fa fa-search"></i>
        <input type="text" class="form-control" placeholder="ค้นหาคอร์สเรียน">
      </div>
    </div>
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <li class="nav-item mx-2">
            <a class="nav-link " aria-current="page" href="{% url 'app:index' %}">หน้าหลัก</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'video:index' %}">คอร์สเรียน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">วิธีใช้งาน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">เกี่ยวกับ</a>
          </li>
        </ul>


        {% if not user.is_authenticated %}
        <a class="btn btn-primary btn-basesign" href="{% url 'app:login' %}">เข้าสู่ระบบ</a>
        {% endif %}
        {% if user.is_authenticated %}




        <div class="dropdown">
          <button class="btn btn-primary btn-profile dropdown mx-2" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-expanded="false">

            <div class="profile_img" >
              {% if member_list.Profile_image %}
              <img src="{{member_list.Profile_image.url}}" alt="" > &nbsp;
              {% endif %}
              {{request.user.email}} &nbsp;
              <i class="fa-solid fa-caret-down"></i>
            </div>

          </button>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
              <a  class="dropdown-item mt-2" href="{% url 'app:profile' %}">ตั้งค่าโปรไฟล์</a>
            </li>
            <li>
                <a type="submit" class="dropdown-item mt-2" href="{% url 'video:management_course' %}">จัดการคอร์ส</a>
            </li>
            <li>
                <form method="post" action="{% url 'app:logout' %}" novalidate>
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item mt-2">ออกระบบ</button>
                </form>
            </li>

          </ul>
        </div>


        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid">

    {% block content %}{% endblock %}
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.all.min.js"></script>
<script>
  $(function(){
    $('.btn-play').on('click',function(){
      var x = $(this).attr('videourl');
      var video = $('#videoplayer')[0];
      video.src = x;
      video.load();
      video.play();
    });
  });
</script>
{% if messages %}
{% for message in messages %}
<script>
  Swal.fire({
  position: 'center',
  icon: 'success',
  title: '{{ message }}',
  showConfirmButton: false,
  timer: 1500
})

</script>
{% endfor %}
{% endif %}


</html>

Jcode/templates/layout/baselogin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}jCode Academy{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kanit&display=swap" rel="stylesheet">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light  bg-white border-bottom mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'app:index' %}">jCode Academy</a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="d-flex">

    </div>
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <li class="nav-item mx-2">
            <a class="nav-link " aria-current="page" href="{% url 'app:index' %}">หน้าหลัก</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">คอร์สเรียน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">วิธีใช้งาน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">เกี่ยวกับ</a>
          </li>
        </ul>

        {% if not user.is_authenticated %}

        <div class="d-flex">
          <a href="{% url 'app:signup' %}" class="btn btn-basesignin mx-2" style="background-color: #5179DC;">สมัครสมาชิก</a>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <span>Hello, {{ request.user.username }}</span>
        <form method="post" action="{% url 'app:logout' %}" novalidate>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mx-2">Log out</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid">

    {% block content %}{% endblock %}
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="{% static 'js/pophover.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</html>

Jcode/templates/layout/basesignup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}jCode Academy{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kanit&display=swap" rel="stylesheet">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/stylesignup.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light  bg-white border-bottom mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'app:index' %}">jCode Academy</a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="d-flex">

    </div>
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <li class="nav-item mx-2">
            <a class="nav-link " aria-current="page" href="{% url 'app:index' %}">หน้าหลัก</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">คอร์สเรียน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">วิธีใช้งาน</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#">เกี่ยวกับ</a>
          </li>
        </ul>

        {% if not user.is_authenticated %}

        <div class="d-flex">
          <a href="{% url 'app:login' %}" class="btn btn-basesignup mx-2" style="background-color: #5179DC;">เข้าสู่ระบบ</a>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <span>Hello, {{ request.user.username }}</span>
        <form method="post" action="{% url 'app:logout' %}" novalidate>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mx-2">Log out</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid">

    {% block content %}{% endblock %}
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="{% static 'js/pophover.js' %}"></script>
</html>